version: '3'
services:
  web:
    build: .
    container_name: pizzeria
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    tty: true
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOST_DEV=${ALLOWED_HOST_DEV}

      # sender mail credential
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

      # stripe
      - STRIPE_TEST_KEY=${STRIPE_TEST_KEY}

      # database settings
      # - NAME=${NAME}
      # - HOST=${HOST}
      # - PORT=${PORT}
      # - USER=${USER_DB}
      # - PASSWORD=${PASSWORD}